#!/usr/bin/env bash
# Transfers a file from our client to a server
FILE=$1
IP=$2
USERNAME=$3
SSKEY_PATH=$4
if [ $# -lt 3 ]
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 4 ]
then
   scp -o StrictHostKeyChecking=no -i "$SSKEY_PATH" "$FILE" "$USERNAME@$IP": 
else
   scp -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP":
fi
