#!/usr/bin/env bash
# Install nginx server
sudo apt-get update
sudo apt-get install nginx -y
# change content of default_server
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
# activate redirect
command="\\\n\t# Redirection\n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/ a $command" /etc/nginx/sites-available/default
# start the daemon
sudo /etc/init.d/nginx restart
