#!/usr/bin/env bash
# Generates a MySQL dump of all DB's and creates a compressed archive out of it
# The archive has the following name format: day-month-year.tar.gz
mysqldump --all-databases -uroot -p"$1" -rbackup.sql
tar -cvzf "$(date +%m-%d-%Y).tar.gz" ./backup.sql
