#!/usr/bin/env bash
# blueprint for an init script
do_start()
{
	./manage_my_process &
	$! > /var/run/my_process.pid
	echo "manage_my_process started"
}

do_stop()
{
	pkill -F /var/run/my_process.pid
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

do_reload()
{
	pkill -F /var/run/my_process.pid
	./manage_my_process &
	$! > /var/run/my_process.pid
	echo "manage_my_process restarted"
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_reload
	;;
  *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac

