#!/usr/bin/env bash
# isplays numbers from 1 to 100 using FizzBuzz game
i=1
while [ $i -le 100 ]
do 
   text=""
   if [ $(( i % 3 )) -eq 0 ]
   then
      text+="Fizz"
   fi
   if [ $(( i % 5 )) -eq 0 ]
   then
      text+="Buzz"
   fi
   if [ $(( i % 3 )) -ne 0 ] && [ $(( i % 5 )) -ne 0 ]
   then
      text+=$i
   fi
   echo $text
   (( i++ ))
done