#!/usr/bin/env bash
# Displays "Holberton School" 10 times and in the 9th iteration "Hi"
i=1
while [ $i -lt 11 ]
do 
   
   if [ $(( i % 8)) -eq 0 ]
   then
      echo "good luck"
   elif [ $(( i % 4)) -eq 0 ]
   then
      echo "bad luck"
   else
      echo "Holberton School"
   fi
   (( i++ ))
done