#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
i=1
j=0
while [ $j -le 12 ]
do 
   echo "Hour: $j"
   while [ $i -le 59 ]
   do
      echo $i
      (( i++ ))
   done
   (( j++ ))
   i=1
done