#!/usr/bin/env bash
# nginx must be running as nginx user and listening on all active IPs on port 8080
pkill -f apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod a+rwx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
